spring:
  datasource:
    username: postgres
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    url: jdbc:postgresql://localhost:5432/goreit
    password: password
  jpa:
    hibernate:
      ddl-auto: create
